name: Validate with hassfest

on:
  push:
    branches:
      - "main"
      - "feat**"  
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v4"
      - name: "Validate Hassfest"
        uses: home-assistant/actions/hassfest@master
